name: netflox
description: Family app to watch movies on media server using TMDB API

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  auto_route: ^5.0.1
  auto_size_text: ^3.0.0
  awesome_dialog: ^3.0.2
  better_player: ^0.0.83
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.3.0
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  dartssh2: ^2.7.2
  email_validator: ^2.0.1
  equatable: ^2.0.5
  firebase_auth: ^3.4.2
  firebase_core: ^1.19.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.10
  group_button: ^5.2.1
  http: ^0.13.4
  nil: ^1.1.1
  path_provider: ^2.0.11
  pointer_interceptor: ^0.9.3+2
  provider: ^6.0.3
  responsive_framework: ^0.2.0
  shared_preferences: ^2.0.15
  shelf: ^1.4.0
  shimmer: ^2.0.0
  universal_io: ^2.0.4
  youtube_player_iframe: ^3.0.4

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: assets/images/launcher/netflox_app_logo_ios.png
  image_path_android: assets/images/launcher/netflox_app_logo_android.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/images/launcher/netflox_foregound.png

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image_dark: assets/images/netflox_dark_small.png
  image: assets/images/netflox_light_small.png
  android_12:
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#000000"
    image_dark: assets/images/launcher/netflox_foregound.png
    image: assets/images/launcher/netflox_foregound.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/launcher/
    - assets/icons/
    - assets/jsons/
